---
- hosts: all
  become: yes
  tasks:
   - name: i want to install webserver
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Redhat" 

   - name: i want to start the server
     service:
      name: apache2
      state: restarted
     when: ansible_os_family == "Redhat"
  

