---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install webserver
     apt:
      name: "{{mywebpackonubuntu}}"
      state: present
     when: ansible_os_family == "Debian"

   - name: i want to start the server
     service:
      name: "{{mywebpackonubuntu}}"
      state: restarted
     when: ansible_os_family == "Debian"

   - name: i want to start the server on redhat node
     yum:
      name: "{{mywebpackonredhat}}"
      state: present
     when: ansible_os_family == "RedHat"

   - name: i want to start webserver in redhat node
     service:
      name: "{{mywebpackonredhat}}"
      state: started
     when: ansible_os_family == "RedHat"
