---
- hosts: all
  become: yes
  tasks:
   - name: i want to install webserver Redhat
     apt:
      name: httpd
      state: present
     when: ansible_os_family == "Redhat" 

   - name: i want to start the server Redhat
     service:
      name: httpd
      state: restarted
     when: ansible_os_family == "Redhat"
  

