---
- hosts: all
  tasks:
   - name: i want to install webserver Redhat
     yum:
      name: httpd
      state: present
     when: ansible_os_family == "Redhat" 

   - name: i want to start the server Redhat
     service:
      name: httpd
      state: started
     when: ansible_os_family == "Redhat"
  

