---
- hosts: all
  become: yes
  tasks: 
   - name: install webserver
     apt:
      name: apache2
      state: present
   - name: start server
     service: 
      name: apache2
      state: restarted 